### ISSUE TITLE
I DON"T HAVE PRIOGREAM

### ISSUE THREAD

**Issue by CatalinTiu** [Fineas/Expression-Parser#1]
PLS UOPLOD PROGERAM, I NEED GOOD MARK AT CHRISTMAS

**Comment by Fineas** [comment]
0d26680587049dd184b363bbcae0d28fabf0725c - Please check the newest update.
It contains both the Truth Table and the True/Flase Atoms.
Make sure to use the proper encoding.

Best of luck with your Christmas.

**Comment by CatalinTiu** [comment]
THANK
